name: Build Kivy Android APK

on:
  push:
    branches:
      - main
  workflow_dispatch:  # allows manual run

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - uses: actions/checkout@v4

      # Debug step to check basic shell commands
      - name: Debug system info
        run: |
          echo "PATH=$PATH"
          which mkdir
          mkdir -p test_dir && echo "mkdir works"

      # Install system dependencies (including coreutils for 'yes')
      - name: Setup system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jdk wget unzip coreutils

      # Download and install Android SDK command line tools + SDK packages
      - name: Setup Android SDK command line tools and packages
        run: |
          /bin/mkdir -p $HOME/android-sdk/cmdline-tools
          /usr/bin/wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
          /usr/bin/unzip cmdline-tools.zip -d $HOME/android-sdk/cmdline-tools
          /bin/mv $HOME/android-sdk/cmdline-tools/cmdline-tools $HOME/android-sdk/cmdline-tools/latest

          export PATH=$HOME/android-sdk/cmdline-tools/latest/bin:$PATH

          yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses
          $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager "platform-tools" "build-tools;33.0.2" "platforms;android-33" "ndk;23.1.7779620" "cmdline-tools;latest"
        env:
          ANDROID_SDK_ROOT: $HOME/android-sdk
          PATH: $HOME/android-sdk/cmdline-tools/latest/bin:$PATH

      # Get current date for cache keys
      - name: Get Date
        id: get-date
        run: echo "date=$(date -u '+%Y%m%d')" >> $GITHUB_OUTPUT

      # Cache global Buildozer directory
      - name: Cache Buildozer global directory
        uses: actions/cache@v4
        with:
          path: .buildozer_global
          key: buildozer-global-${{ hashFiles('buildozer.spec') }}

      # Cache local Buildozer build directory
      - name: Cache Buildozer local directory
        uses: actions/cache@v4
        with:
          path: .buildozer
          key: ${{ runner.os }}-${{ steps.get-date.outputs.date }}-${{ hashFiles('buildozer.spec') }}

      # Run Buildozer to build APK
      - name: Build APK with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        env:
          ANDROID_SDK_ROOT: $HOME/android-sdk
          ANDROID_HOME: $HOME/android-sdk
          PATH: $HOME/android-sdk/cmdline-tools/latest/bin:$HOME/android-sdk/platform-tools:$HOME/android-sdk/build-tools/33.0.2:$PATH
        with:
          command: buildozer android debug
          buildozer_version: master

      # Upload APK artifact
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: kivy-apk
          path: ${{ steps.buildozer.outputs.filename }}
