name: Build Kivy Android APK

on:
  push:
    branches:
      - main
  workflow_dispatch:  # allows manual run

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - uses: actions/checkout@v4

      # Get date for caching
      - name: Get Date
        id: get-date
        run: echo "date=$(date -u '+%Y%m%d')" >> $GITHUB_OUTPUT

      # Cache Buildozer global directory
      - name: Cache Buildozer global directory
        uses: actions/cache@v4
        with:
          path: .buildozer_global
          key: buildozer-global-${{ hashFiles('buildozer.spec') }}

      # Cache local buildozer directory (daily cache key to avoid conflicts)
      - name: Cache Buildozer local directory
        uses: actions/cache@v4
        with:
          path: .buildozer
          key: ${{ runner.os }}-${{ steps.get-date.outputs.date }}-${{ hashFiles('buildozer.spec') }}

      # Build with Buildozer
      - name: Build APK
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          command: buildozer android debug
          buildozer_version: master

      # Upload APK as artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: kivy-apk
          path: ${{ steps.buildozer.outputs.filename }}
